Publish

diff --git a/maps-tools b/maps-tools
--- a/maps-tools
+++ b/maps-tools
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 #needs to increment on every change!!!
-#version: 14
+#version: 15
 
 #initialize variables
 readonly DEFAULT_DOCKER_IMAGE_REGISTRY="ghcr.io/spring-media"
@@ -17,6 +17,8 @@ CREATE_DAEMON_CONTAINER=false
 CONTAINER_ATTACH=false
 AZURE_LOGIN=false
 AZURE_LOGIN_ROLE=Developer
+SSO_LOGIN=false
+SSO_LOGIN_ROLE=NMT-dev
 UPDATE=false
 USER_NAME=${HOME##*/}
 declare -a ADDITIONAL_CONTAINER_ARGS
@@ -35,7 +37,8 @@ function print_usage() {
   echo '-i: Ask for a local Docker image to use'
   echo '-d: create daemon container that runs in the background, so you can use docker exec to connect to'
   echo '-a: attach to daemon container that previously created with -d option'
-  echo '-l: (EXPERIMENTAL) test option to login with AZURE AD, default role is Developer, you can also specify default assume role: Admin, Developer, OnlyViewer after parameter, e.g. -l Admin'
+  echo '-l: (EXPERIMENTAL/DEPRECATED) test option to login with AZURE AD, default role is Developer, you can also specify default assume role: Admin, Developer, OnlyViewer after parameter, e.g. -l Admin'
+  echo '-L: (BETA) option to login with AWS SSO AD LOGIN, default role is "NMT-dev", you can also specify default assume role: NMT-admin, NMT-dev, NMT-vieweronly after parameter, e.g. -L NMT-admin'
   echo '-o: add aditional cmd parameter to docker run/create command, IMPORTANT: use double quotes! you can use this option more than one time, e.g. -o "-p 2222:22" -o "-e DISPLAY=host.docker.internal:0"'
   echo '-u: update maps-tools and docker image (force pull)'
   echo
@@ -55,9 +58,9 @@ function create_docker_run_command() {
       fi
       if [[ "${USE_AWS_VOLUME}" == true ]]
       then
-        docker_string="docker create --name maps-tools ${volumes[*]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} --entrypoint \"/init/init_daemon.sh\" $image_name"
+        docker_string="docker create --name maps-tools ${volumes[*]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"SSO_LOGIN_ROLE=$SSO_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" -e \"SSO_LOGIN=$SSO_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} --entrypoint \"/init/init_daemon.sh\" $image_name"
       else
-        docker_string="docker create --name maps-tools ${volumes[1]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} --entrypoint \"/init/init_daemon.sh\" $image_name"
+        docker_string="docker create --name maps-tools ${volumes[1]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"SSO_LOGIN_ROLE=$SSO_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" -e \"SSO_LOGIN=$SSO_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} --entrypoint \"/init/init_daemon.sh\" $image_name"
       fi
       ;;
     "$CONTAINER_ATTACH")
@@ -72,9 +75,9 @@ function create_docker_run_command() {
     *)
       if [[ "${USE_AWS_VOLUME}" == true ]]
       then
-        docker_string="docker run -it --rm ${volumes[*]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} $image_name"
+        docker_string="docker run -it --rm ${volumes[*]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"SSO_LOGIN_ROLE=$SSO_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" -e \"SSO_LOGIN=$SSO_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} $image_name"
       else
-        docker_string="docker run -it --rm ${volumes[1]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} $image_name"
+        docker_string="docker run -it --rm ${volumes[1]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"SSO_LOGIN_ROLE=$SSO_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" -e \"SSO_LOGIN=$SSO_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} $image_name"
       fi
       ;;
   esac
@@ -172,7 +175,7 @@ function getopts_get_optional_argument() {
 }
 
 # Parse flags
-while getopts "b:o:he:ivdaul" argument; do
+while getopts "b:o:he:ivdaulL" argument; do
   case "${argument}" in
     b)
       # Will be eventually used for additional BUILD ARGs later. Currently, the only BUILD ARG is directly
@@ -201,10 +204,15 @@ while getopts "b:o:he:ivdaul" argument; do
       if [[ "$arch" == "amd64" || "$arch" == "x86_64" ]]; then
         AZURE_LOGIN=true;
       else
-        echo "╔════════════════════════════════════════════════════════════════════╗"
-        echo "║⚠️ CPU ARCHITECTURE NOT SUPPORTED FOR AZURE LOGIN! USING ADFS INSTEAD║"
-        echo "╚════════════════════════════════════════════════════════════════════╝"
+        echo "╔═══════════════════════════════════════════════════════════════════════════╗"
+        echo "║⚠️ CPU ARCHITECTURE NOT SUPPORTED FOR AZURE LOGIN! USING ADFS OR SSO INSTEAD║"
+        echo "╚═══════════════════════════════════════════════════════════════════════════╝"
       fi
+      ;;
+    L)
+      getopts_get_optional_argument $@
+      SSO_LOGIN_ROLE=${OPTARG}
+      SSO_LOGIN=true;
       ;;
     u)
       UPDATE=true
@@ -250,6 +258,13 @@ elif [ -x /usr/local/bin/maps-tools ] && [ "${0##*/}" != "maps-tools" ]; then
   docker_pull
   exit 0
 fi
+
+#don't use -l and -L options together
+if [[ "${AZURE_LOGIN}" == true && "${SSO_LOGIN}" == true ]]
+  then
+    echo "you cannot use -l and -L Option simultaneously, you need to decide which login option you want"
+    exit 1
+  fi
 
 #check docker is installed
 if [ ! -d "/Applications/Docker.app" ]; then
